"""add_event_messages_table

Revision ID: a94659fcf646
Revises: d7397546d8ab
Create Date: 2026-02-16 02:00:24.498714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94659fcf646'
down_revision: Union[str, None] = 'd7397546d8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_messages',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('message_type', sa.dialects.postgresql.ENUM('TEXT', 'SYSTEM', name='messagetype', create_type=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['travel_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_messages_event_id'), 'event_messages', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_messages_id'), 'event_messages', ['id'], unique=False)
    op.create_index(op.f('ix_event_messages_sender_id'), 'event_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_event_messages_tenant_id'), 'event_messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_event_participants_id'), 'event_participants', ['id'], unique=False)
    op.create_index(op.f('ix_group_messages_id'), 'group_messages', ['id'], unique=False)
    op.create_index(op.f('ix_travel_events_group_id'), 'travel_events', ['group_id'], unique=False)
    op.create_index(op.f('ix_travel_events_id'), 'travel_events', ['id'], unique=False)
    op.create_index(op.f('ix_travel_events_start_time'), 'travel_events', ['start_time'], unique=False)
    op.create_index(op.f('ix_travel_events_tenant_id'), 'travel_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_events_tenant_id'), table_name='travel_events')
    op.drop_index(op.f('ix_travel_events_start_time'), table_name='travel_events')
    op.drop_index(op.f('ix_travel_events_id'), table_name='travel_events')
    op.drop_index(op.f('ix_travel_events_group_id'), table_name='travel_events')
    op.drop_index(op.f('ix_group_messages_id'), table_name='group_messages')
    op.drop_index(op.f('ix_event_participants_id'), table_name='event_participants')
    op.drop_index(op.f('ix_event_messages_tenant_id'), table_name='event_messages')
    op.drop_index(op.f('ix_event_messages_sender_id'), table_name='event_messages')
    op.drop_index(op.f('ix_event_messages_id'), table_name='event_messages')
    op.drop_index(op.f('ix_event_messages_event_id'), table_name='event_messages')
    op.drop_table('event_messages')
    # ### end Alembic commands ###
