"""add_live_locations_table

Revision ID: 5ab969fbe017
Revises: a94659fcf646
Create Date: 2026-02-16 12:45:44.808233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab969fbe017'
down_revision: Union[str, None] = 'a94659fcf646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_locations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['travel_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_live_location_event_user')
    )
    op.create_index('idx_live_location_event_active', 'live_locations', ['event_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_live_locations_event_id'), 'live_locations', ['event_id'], unique=False)
    op.create_index(op.f('ix_live_locations_id'), 'live_locations', ['id'], unique=False)
    op.create_index(op.f('ix_live_locations_tenant_id'), 'live_locations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_live_locations_user_id'), 'live_locations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_locations_user_id'), table_name='live_locations')
    op.drop_index(op.f('ix_live_locations_tenant_id'), table_name='live_locations')
    op.drop_index(op.f('ix_live_locations_id'), table_name='live_locations')
    op.drop_index(op.f('ix_live_locations_event_id'), table_name='live_locations')
    op.drop_index('idx_live_location_event_active', table_name='live_locations')
    op.drop_table('live_locations')
    # ### end Alembic commands ###
