"""Add cascade delete to notifications

Revision ID: 75231acb3cb4
Revises: e75605af8d8c
Create Date: 2026-02-19 10:52:31.170846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75231acb3cb4'
down_revision: Union[str, None] = 'e75605af8d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notifications_receiver_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_receiver_id_fkey'), 'notifications', 'users', ['receiver_id'], ['id'])
    # ### end Alembic commands ###
