"""Add token blacklist table for JWT revocation

Revision ID: 4699914b3f4a
Revises: ed2d05d6e9a1
Create Date: 2026-02-08 14:01:13.585419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4699914b3f4a'
down_revision: Union[str, None] = 'ed2d05d6e9a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
